"""Added field version to Product

Revision ID: 2e84478e0fa2
Revises: 80cbc4ac4346
Create Date: 2026-03-09 10:29:53.923450

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "2e84478e0fa2"
down_revision: Union[str, Sequence[str], None] = "80cbc4ac4346"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("order_lines", sa.Column("order_id", sa.String(length=255), nullable=True))
    op.drop_column("order_lines", "orderId")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("order_lines", sa.Column("orderId", sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.drop_column("order_lines", "order_id")
    # ### end Alembic commands ###
