"""Added table allocations_view for Read-Only operations

Revision ID: 3e1d789d1854
Revises: 5c975840647b
Create Date: 2026-03-09 12:33:22.889012

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "3e1d789d1854"
down_revision: Union[str, Sequence[str], None] = "5c975840647b"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "allocations_view",
        sa.Column("order_id", sa.String(length=255), nullable=True),
        sa.Column("sku", sa.String(length=255), nullable=True),
        sa.Column("batch_ref", sa.String(length=255), nullable=True),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("allocations_view")
    # ### end Alembic commands ###
