"""Initial schema with Product aggregate

Revision ID: 4837ce3bc6b4
Revises:
Create Date: 2026-02-02 16:04:04.362824

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "4837ce3bc6b4"
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table("products", sa.Column("sku", sa.String(length=255), nullable=False), sa.PrimaryKeyConstraint("sku"))
    op.create_foreign_key(None, "batches", "products", ["sku"], ["sku"])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "batches", type_="foreignkey")  # type: ignore
    op.drop_table("products")
    # ### end Alembic commands ###
