"""Renamed batchref to batch_ref everywhere

Revision ID: 5c975840647b
Revises: 2e84478e0fa2
Create Date: 2026-03-09 12:20:24.356993

"""

from typing import Sequence, Union

# revision identifiers, used by Alembic.
revision: str = "5c975840647b"
down_revision: Union[str, Sequence[str], None] = "2e84478e0fa2"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
