"""Added field version to Product

Revision ID: 80cbc4ac4346
Revises: 4837ce3bc6b4
Create Date: 2026-02-04 12:54:38.374042

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "80cbc4ac4346"
down_revision: Union[str, Sequence[str], None] = "4837ce3bc6b4"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("products", sa.Column("version_number", sa.Integer(), server_default="0", nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("products", "version_number")
    # ### end Alembic commands ###
